name: "Shellcheck"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: sudo apt-get install shellcheck
      - run: shellcheck -f json bin/common.sh > license-go.json || pwd
      - name: create sarif file
        uses: lvyinggithub/json-to-sarif-actions@main
        with:
          json_file_path: "./license-go.json"
          licens_sarif_path: "./1.sarif"
      - name: cat sarif
        run: cat ./1.sarif
      - name: upload  scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./1.sarif

