name: "Shellcheck"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  upload-sarif:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - run: sudo apt-get install shellcheck
      - run: shellcheck -f json extra/datadog.sh > result.json || pwd
      - uses: lvyinggithub/json-to-sarif-actions@main
        with:
          json_file_path: "result.json"
          licens_sarif_path: "result.sarif"
      - name: cat sarif
        run: cat result.json
      - name: upload  scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: result.sarif          
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
